USE kebrchacha;

-- Fill all 50 numbers for room 7 with verified tickets from existing users
INSERT IGNORE INTO tickets (room_id, user_id, number, status)
SELECT 7, u.id, n.num, 'verified'
FROM (
  SELECT  1 AS num UNION SELECT  2 UNION SELECT  3 UNION SELECT  4 UNION SELECT  5
  UNION SELECT  6 UNION SELECT  7 UNION SELECT  8 UNION SELECT  9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15
  UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25
  UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35
  UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45
  UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) n
JOIN (
  SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
  FROM users WHERE telegram_id >= 100000001
) u ON u.rn = ((n.num - 1) % 30) + 1;

-- Lock the room
UPDATE rooms SET filled_slots = 50, status = 'locked' WHERE id = 7;

-- Confirm
SELECT r.id, r.title, r.filled_slots, r.status,
       COUNT(t.id) as ticket_count
FROM rooms r
LEFT JOIN tickets t ON t.room_id = r.id AND t.status = 'verified'
WHERE r.id = 7
GROUP BY r.id;
